#include <OpenGL/gl.h>
// #include <OpenGL/GL.h>
#include <cstdio>

extern void glInterfaceAccum (GLenum op, GLfloat value);
extern void glInterfaceAlphaFunc (GLenum func, GLclampf ref);
extern GLboolean glInterfaceAreTexturesResident (GLsizei n, const GLuint *textures, GLboolean *residences);
extern void glInterfaceArrayElement (GLint i);
extern void glInterfaceBegin (GLenum mode);
extern void glInterfaceBindTexture (GLenum target, GLuint texture);
extern void glInterfaceBitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
extern void glInterfaceBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
extern void glInterfaceBlendEquation (GLenum mode);
extern void glInterfaceBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha);
extern void glInterfaceBlendFunc (GLenum sfactor, GLenum dfactor);
extern void glInterfaceCallList (GLuint list);
extern void glInterfaceCallLists (GLsizei n, GLenum type, const GLvoid *lists);
extern void glInterfaceClear (GLbitfield mask);
extern void glInterfaceClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void glInterfaceClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
extern void glInterfaceClearDepth (GLclampd depth);
extern void glInterfaceClearIndex (GLfloat c);
extern void glInterfaceClearStencil (GLint s);
extern void glInterfaceClipPlane (GLenum plane, const GLdouble *equation);
extern void glInterfaceColor (GLbyte red, GLbyte green, GLbyte blue);
extern void glInterfaceColor (const GLbyte *v);
extern void glInterfaceColor (GLdouble red, GLdouble green, GLdouble blue);
extern void glInterfaceColor (const GLdouble *v);
extern void glInterfaceColor (GLfloat red, GLfloat green, GLfloat blue);
extern void glInterfaceColor (const GLfloat *v);
extern void glInterfaceColor (GLint red, GLint green, GLint blue);
extern void glInterfaceColor (const GLint *v);
extern void glInterfaceColor (GLshort red, GLshort green, GLshort blue);
extern void glInterfaceColor (const GLshort *v);
extern void glInterfaceColor (GLubyte red, GLubyte green, GLubyte blue);
extern void glInterfaceColor (const GLubyte *v);
extern void glInterfaceColor (GLuint red, GLuint green, GLuint blue);
extern void glInterfaceColor (const GLuint *v);
extern void glInterfaceColor (GLushort red, GLushort green, GLushort blue);
extern void glInterfaceColor (const GLushort *v);
extern void glInterfaceColor (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
extern void glInterfaceColor (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
extern void glInterfaceColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void glInterfaceColor (GLint red, GLint green, GLint blue, GLint alpha);
extern void glInterfaceColor (GLshort red, GLshort green, GLshort blue, GLshort alpha);
extern void glInterfaceColor (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
extern void glInterfaceColor (GLuint red, GLuint green, GLuint blue, GLuint alpha);
extern void glInterfaceColor (GLushort red, GLushort green, GLushort blue, GLushort alpha);
extern void glInterfaceColor4 (const GLbyte *v);
extern void glInterfaceColor4 (const GLdouble *v);
extern void glInterfaceColor4 (const GLfloat *v);
extern void glInterfaceColor4 (const GLint *v);
extern void glInterfaceColor4 (const GLshort *v);
extern void glInterfaceColor4 (const GLubyte *v);
extern void glInterfaceColor4 (const GLuint *v);
extern void glInterfaceColor4 (const GLushort *v);
extern void glInterfaceColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void glInterfaceColorMaterial (GLenum face, GLenum mode);
extern void glInterfaceColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void glInterfaceColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data);
extern void glInterfaceColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table);
extern void glInterfaceColorTableParameter (GLenum target, GLenum pname, const GLfloat *params);
extern void glInterfaceColorTableParameter (GLenum target, GLenum pname, const GLint *params);
extern void glInterfaceConvolutionFilter (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image);
extern void glInterfaceConvolutionFilter (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, GLfloat params);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, const GLfloat *params);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, GLint params);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, const GLint *params);
extern void glInterfaceCopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyConvolutionFilter (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyConvolutionFilter (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glInterfaceCopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
extern void glInterfaceCopyTexImage (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
extern void glInterfaceCopyTexImage (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void glInterfaceCopyTexSubImage (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyTexSubImage (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glInterfaceCopyTexSubImage (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glInterfaceCullFace (GLenum mode);
extern void glInterfaceDeleteLists (GLuint list, GLsizei range);
extern void glInterfaceDeleteTextures (GLsizei n, const GLuint *textures);
extern void glInterfaceDepthFunc (GLenum func);
extern void glInterfaceDepthMask (GLboolean flag);
extern void glInterfaceDepthRange (GLclampd zNear, GLclampd zFar);
extern void glInterfaceDisable (GLenum cap);
extern void glInterfaceDisableClientState (GLenum array);
extern void glInterfaceDrawArrays (GLenum mode, GLint first, GLsizei count);
extern void glInterfaceDrawBuffer (GLenum mode);
extern void glInterfaceDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
extern void glInterfaceDrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
extern void glInterfaceDrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices);
extern void glInterfaceEdgeFlag (GLboolean flag);
extern void glInterfaceEdgeFlag (GLsizei stride, const GLvoid *pointer);
extern void glInterfaceEdgeFlag (const GLboolean *flag);
extern void glInterfaceEnable (GLenum cap);
extern void glInterfaceEnableClientState (GLenum array);
extern void glInterfaceEnd (void);
extern void glInterfaceEndList (void);
extern void glInterfaceEvalCoord (GLdouble u);
extern void glInterfaceEvalCoord (const GLdouble *u);
extern void glInterfaceEvalCoord (GLfloat u);
extern void glInterfaceEvalCoord (const GLfloat *u);
extern void glInterfaceEvalCoord (GLdouble u, GLdouble v);
extern void glInterfaceEvalCoord (GLfloat u, GLfloat v);
extern void glInterfaceEvalCoord2 (const GLdouble *u);
extern void glInterfaceEvalCoord2 (const GLfloat *u);
extern void glInterfaceEvalMesh (GLenum mode, GLint i1, GLint i2);
extern void glInterfaceEvalMesh (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
extern void glInterfaceEvalPoint (GLint i);
extern void glInterfaceEvalPoint (GLint i, GLint j);
extern void glInterfaceFeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer);
extern void glInterfaceFinish (void);
extern void glInterfaceFlush (void);
extern void glInterfaceFog (GLenum pname, GLfloat param);
extern void glInterfaceFog (GLenum pname, const GLfloat *params);
extern void glInterfaceFog (GLenum pname, GLint param);
extern void glInterfaceFog (GLenum pname, const GLint *params);
extern void glInterfaceFrontFace (GLenum mode);
extern void glInterfaceFrustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern GLuint glInterfaceGenLists (GLsizei range);
extern void glInterfaceGenTextures (GLsizei n, GLuint *textures);
extern void glInterfaceGetBooleanv (GLenum pname, GLboolean *params);
extern void glInterfaceGetClipPlane (GLenum plane, GLdouble *equation);
extern void glInterfaceGetColorTable (GLenum target, GLenum format, GLenum type, GLvoid *table);
extern void glInterfaceGetColorTableParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetColorTableParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetConvolutionFilter (GLenum target, GLenum format, GLenum type, GLvoid *image);
extern void glInterfaceGetConvolutionParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetConvolutionParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetDoublev (GLenum pname, GLdouble *params);
extern GLenum glInterfaceGetError (void);
extern void glInterfaceGetFloatv (GLenum pname, GLfloat *params);
extern void glInterfaceGetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values);
extern void glInterfaceGetHistogramParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetHistogramParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetIntegerv (GLenum pname, GLint *params);
extern void glInterfaceGetLight (GLenum light, GLenum pname, GLfloat *params);
extern void glInterfaceGetLight (GLenum light, GLenum pname, GLint *params);
extern void glInterfaceGetMap (GLenum target, GLenum query, GLdouble *v);
extern void glInterfaceGetMap (GLenum target, GLenum query, GLfloat *v);
extern void glInterfaceGetMap (GLenum target, GLenum query, GLint *v);
extern void glInterfaceGetMaterial (GLenum face, GLenum pname, GLfloat *params);
extern void glInterfaceGetMaterial (GLenum face, GLenum pname, GLint *params);
extern void glInterfaceGetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values);
extern void glInterfaceGetMinmaxParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetMinmaxParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetPixelMap (GLenum map, GLfloat *values);
extern void glInterfaceGetPixelMap (GLenum map, GLuint *values);
extern void glInterfaceGetPixelMap (GLenum map, GLushort *values);
extern void glInterfaceGetPointerv (GLenum pname, GLvoid **params);
extern void glInterfaceGetPolygonStipple (GLubyte *mask);
extern void glInterfaceGetSeparableFilter (GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span);
extern const GLubyte *glInterfaceGetString (GLenum name);
extern void glInterfaceGetTexEnv (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetTexEnv (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetTexGen (GLenum coord, GLenum pname, GLdouble *params);
extern void glInterfaceGetTexGen (GLenum coord, GLenum pname, GLfloat *params);
extern void glInterfaceGetTexGen (GLenum coord, GLenum pname, GLint *params);
extern void glInterfaceGetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
extern void glInterfaceGetTexLevelParameter (GLenum target, GLint level, GLenum pname, GLfloat *params);
extern void glInterfaceGetTexLevelParameter (GLenum target, GLint level, GLenum pname, GLint *params);
extern void glInterfaceGetTexParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetTexParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceHint (GLenum target, GLenum mode);
extern void glInterfaceHistogram (GLenum target, GLsizei width, GLenum internalformat, GLboolean sink);
extern void glInterfaceIndexMask (GLuint mask);
extern void glInterfaceIndexPointer (GLenum type, GLsizei stride, const GLvoid *pointer);
extern void glInterfaceIndex (GLdouble c);
extern void glInterfaceIndex (const GLdouble *c);
extern void glInterfaceIndex (GLfloat c);
extern void glInterfaceIndex (const GLfloat *c);
extern void glInterfaceIndex (GLint c);
extern void glInterfaceIndex (const GLint *c);
extern void glInterfaceIndex (GLshort c);
extern void glInterfaceIndex (const GLshort *c);
extern void glInterfaceIndex (GLubyte c);
extern void glInterfaceIndex (const GLubyte *c);
extern void glInterfaceInitNames (void);
extern void glInterfaceInterleavedArrays (GLenum format, GLsizei stride, const GLvoid *pointer);
extern GLboolean glInterfaceIsEnabled (GLenum cap);
extern GLboolean glInterfaceIsList (GLuint list);
extern GLboolean glInterfaceIsTexture (GLuint texture);
extern void glInterfaceLightModel (GLenum pname, GLfloat param);
extern void glInterfaceLightModel (GLenum pname, const GLfloat *params);
extern void glInterfaceLightModel (GLenum pname, GLint param);
extern void glInterfaceLightModel (GLenum pname, const GLint *params);
extern void glInterfaceLight (GLenum light, GLenum pname, GLfloat param);
extern void glInterfaceLight (GLenum light, GLenum pname, const GLfloat *params);
extern void glInterfaceLight (GLenum light, GLenum pname, GLint param);
extern void glInterfaceLight (GLenum light, GLenum pname, const GLint *params);
extern void glInterfaceLineStipple (GLint factor, GLushort pattern);
extern void glInterfaceLineWidth (GLfloat width);
extern void glInterfaceListBase (GLuint base);
extern void glInterfaceLoadIdentity (void);
extern void glInterfaceLoadMatrix (const GLdouble *m);
extern void glInterfaceLoadMatrix (const GLfloat *m);
extern void glInterfaceLoadName (GLuint name);
extern void glInterfaceLogicOp (GLenum opcode);
extern void glInterfaceMap (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
extern void glInterfaceMap (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
extern void glInterfaceMap (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
extern void glInterfaceMap (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
extern void glInterfaceMapGrid (GLint un, GLdouble u1, GLdouble u2);
extern void glInterfaceMapGrid (GLint un, GLfloat u1, GLfloat u2);
extern void glInterfaceMapGrid (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
extern void glInterfaceMapGrid (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
extern void glInterfaceMaterial (GLenum face, GLenum pname, GLfloat param);
extern void glInterfaceMaterial (GLenum face, GLenum pname, const GLfloat *params);
extern void glInterfaceMaterial (GLenum face, GLenum pname, GLint param);
extern void glInterfaceMaterial (GLenum face, GLenum pname, const GLint *params);
extern void glInterfaceMatrixMode (GLenum mode);
extern void glInterfaceMinmax (GLenum target, GLenum internalformat, GLboolean sink);
extern void glInterfaceMultMatrix (const GLdouble *m);
extern void glInterfaceMultMatrix (const GLfloat *m);
extern void glInterfaceNewList (GLuint list, GLenum mode);
extern void glInterfaceNormal (GLbyte nx, GLbyte ny, GLbyte nz);
extern void glInterfaceNormal (const GLbyte *v);
extern void glInterfaceNormal (GLdouble nx, GLdouble ny, GLdouble nz);
extern void glInterfaceNormal (const GLdouble *v);
extern void glInterfaceNormal (GLfloat nx, GLfloat ny, GLfloat nz);
extern void glInterfaceNormal (const GLfloat *v);
extern void glInterfaceNormal (GLint nx, GLint ny, GLint nz);
extern void glInterfaceNormal (const GLint *v);
extern void glInterfaceNormal (GLshort nx, GLshort ny, GLshort nz);
extern void glInterfaceNormal (const GLshort *v);
extern void glInterfaceNormalPointer (GLenum type, GLsizei stride, const GLvoid *pointer);
extern void glInterfaceOrtho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern void glInterfacePassThrough (GLfloat token);
extern void glInterfacePixelMap (GLenum map, GLint mapsize, const GLfloat *values);
extern void glInterfacePixelMap (GLenum map, GLint mapsize, const GLuint *values);
extern void glInterfacePixelMap (GLenum map, GLint mapsize, const GLushort *values);
extern void glInterfacePixelStore (GLenum pname, GLfloat param);
extern void glInterfacePixelStore (GLenum pname, GLint param);
extern void glInterfacePixelTransfer (GLenum pname, GLfloat param);
extern void glInterfacePixelTransfer (GLenum pname, GLint param);
extern void glInterfacePixelZoom (GLfloat xfactor, GLfloat yfactor);
extern void glInterfacePointSize (GLfloat size);
extern void glInterfacePolygonMode (GLenum face, GLenum mode);
extern void glInterfacePolygonOffset (GLfloat factor, GLfloat units);
extern void glInterfacePolygonStipple (const GLubyte *mask);
extern void glInterfacePopAttrib (void);
extern void glInterfacePopClientAttrib (void);
extern void glInterfacePopMatrix (void);
extern void glInterfacePopName (void);
extern void glInterfacePrioritizeTextures (GLsizei n, const GLuint *textures, const GLclampf *priorities);
extern void glInterfacePushAttrib (GLbitfield mask);
extern void glInterfacePushClientAttrib (GLbitfield mask);
extern void glInterfacePushMatrix (void);
extern void glInterfacePushName (GLuint name);
extern void glInterfaceRasterPos (GLdouble x, GLdouble y);
extern void glInterfaceRasterPos (const GLdouble *v);
extern void glInterfaceRasterPos (GLfloat x, GLfloat y);
extern void glInterfaceRasterPos (const GLfloat *v);
extern void glInterfaceRasterPos (GLint x, GLint y);
extern void glInterfaceRasterPos (const GLint *v);
extern void glInterfaceRasterPos (GLshort x, GLshort y);
extern void glInterfaceRasterPos (const GLshort *v);
extern void glInterfaceRasterPos3 (GLdouble x, GLdouble y, GLdouble z);
extern void glInterfaceRasterPos3 (const GLdouble *v);
extern void glInterfaceRasterPos3 (GLfloat x, GLfloat y, GLfloat z);
extern void glInterfaceRasterPos3 (const GLfloat *v);
extern void glInterfaceRasterPos3 (GLint x, GLint y, GLint z);
extern void glInterfaceRasterPos3 (const GLint *v);
extern void glInterfaceRasterPos3 (GLshort x, GLshort y, GLshort z);
extern void glInterfaceRasterPos3 (const GLshort *v);
extern void glInterfaceRasterPos4 (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void glInterfaceRasterPos4 (const GLdouble *v);
extern void glInterfaceRasterPos4 (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void glInterfaceRasterPos4 (const GLfloat *v);
extern void glInterfaceRasterPos4 (GLint x, GLint y, GLint z, GLint w);
extern void glInterfaceRasterPos4 (const GLint *v);
extern void glInterfaceRasterPos4 (GLshort x, GLshort y, GLshort z, GLshort w);
extern void glInterfaceRasterPos4 (const GLshort *v);
extern void glInterfaceReadBuffer (GLenum mode);
extern void glInterfaceReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
extern void glInterfaceRect (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
extern void glInterfaceRect (const GLdouble *v1, const GLdouble *v2);
extern void glInterfaceRect (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
extern void glInterfaceRect (const GLfloat *v1, const GLfloat *v2);
extern void glInterfaceRect (GLint x1, GLint y1, GLint x2, GLint y2);
extern void glInterfaceRect (const GLint *v1, const GLint *v2);
extern void glInterfaceRect (GLshort x1, GLshort y1, GLshort x2, GLshort y2);
extern void glInterfaceRect (const GLshort *v1, const GLshort *v2);
extern GLint glInterfaceRenderMode (GLenum mode);

