#include <OpenGL/gl.h>
#include <cstdio>

extern void glInterfaceAccum (GLenum op, GLfloat value);

extern void glInterfaceColor (GLbyte red, GLbyte green, GLbyte blue);
extern void glInterfaceColor (const GLbyte *v);
extern void glInterfaceColor (GLdouble red, GLdouble green, GLdouble blue);
extern void glInterfaceColor (const GLdouble *v);
extern void glInterfaceColor (GLfloat red, GLfloat green, GLfloat blue);
extern void glInterfaceColor (const GLfloat *v);
extern void glInterfaceColor (GLint red, GLint green, GLint blue);
extern void glInterfaceColor (const GLint *v);
extern void glInterfaceColor (GLshort red, GLshort green, GLshort blue);
extern void glInterfaceColor (const GLshort *v);
extern void glInterfaceColor (GLubyte red, GLubyte green, GLubyte blue);
extern void glInterfaceColor (const GLubyte *v);
extern void glInterfaceColor (GLuint red, GLuint green, GLuint blue);
extern void glInterfaceColor (const GLuint *v);
extern void glInterfaceColor (GLushort red, GLushort green, GLushort blue);
extern void glInterfaceColor (const GLushort *v);
extern void glInterfaceColor (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
extern void glInterfaceColor (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
extern void glInterfaceColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void glInterfaceColor (GLint red, GLint green, GLint blue, GLint alpha);
extern void glInterfaceColor (GLshort red, GLshort green, GLshort blue, GLshort alpha);
extern void glInterfaceColor (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
extern void glInterfaceColor (GLuint red, GLuint green, GLuint blue, GLuint alpha);
extern void glInterfaceColor (GLushort red, GLushort green, GLushort blue, GLushort alpha);
extern void glInterfaceColor4 (const GLbyte *v);
extern void glInterfaceColor4 (const GLdouble *v);
extern void glInterfaceColor4 (const GLfloat *v);
extern void glInterfaceColor4 (const GLint *v);
extern void glInterfaceColor4 (const GLshort *v);
extern void glInterfaceColor4 (const GLubyte *v);
extern void glInterfaceColor4 (const GLuint *v);
extern void glInterfaceColor4 (const GLushort *v);
extern void glInterfaceColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void glInterfaceColorMaterial (GLenum face, GLenum mode);
extern void glInterfaceColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void glInterfaceColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data);
extern void glInterfaceColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table);
extern void glInterfaceColorTableParameter (GLenum target, GLenum pname, const GLfloat *params);
extern void glInterfaceColorTableParameter (GLenum target, GLenum pname, const GLint *params);
extern void glInterfaceConvolutionFilter (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image);
extern void glInterfaceConvolutionFilter (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, GLfloat params);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, const GLfloat *params);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, GLint params);
extern void glInterfaceConvolutionParameter (GLenum target, GLenum pname, const GLint *params);
extern void glInterfaceCopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyConvolutionFilter (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyConvolutionFilter (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glInterfaceCopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
extern void glInterfaceCopyTexImage (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
extern void glInterfaceCopyTexImage (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void glInterfaceCopyTexSubImage (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
extern void glInterfaceCopyTexSubImage (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glInterfaceCopyTexSubImage (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void glInterfaceCullFace (GLenum mode);
extern void glInterfaceDeleteLists (GLuint list, GLsizei range);
extern void glInterfaceDeleteTextures (GLsizei n, const GLuint *textures);
extern void glInterfaceDepthFunc (GLenum func);
extern void glInterfaceDepthMask (GLboolean flag);
extern void glInterfaceDepthRange (GLclampd zNear, GLclampd zFar);
extern void glInterfaceDisable (GLenum cap);
extern void glInterfaceDisableClientState (GLenum array);
extern void glInterfaceDrawArrays (GLenum mode, GLint first, GLsizei count);
extern void glInterfaceDrawBuffer (GLenum mode);
extern void glInterfaceDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
extern void glInterfaceDrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
extern void glInterfaceDrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices);
extern void glInterfaceEdgeFlag (GLboolean flag);
extern void glInterfaceEdgeFlag (GLsizei stride, const GLvoid *pointer);
extern void glInterfaceEdgeFlag (const GLboolean *flag);
extern void glInterfaceEnable (GLenum cap);
extern void glInterfaceEnableClientState (GLenum array);
extern void glInterfaceEnd (void);
extern void glInterfaceEndList (void);
extern void glInterfaceEvalCoord (GLdouble u);
extern void glInterfaceEvalCoord (const GLdouble *u);
extern void glInterfaceEvalCoord (GLfloat u);
extern void glInterfaceEvalCoord (const GLfloat *u);
extern void glInterfaceEvalCoord (GLdouble u, GLdouble v);
extern void glInterfaceEvalCoord (GLfloat u, GLfloat v);
extern void glInterfaceEvalCoord2 (const GLdouble *u);
extern void glInterfaceEvalCoord2 (const GLfloat *u);
extern void glInterfaceEvalMesh (GLenum mode, GLint i1, GLint i2);
extern void glInterfaceEvalMesh (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
extern void glInterfaceEvalPoint (GLint i);
extern void glInterfaceEvalPoint (GLint i, GLint j);
extern void glInterfaceFeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer);
extern void glInterfaceFinish (void);
extern void glInterfaceFlush (void);
extern void glInterfaceFog (GLenum pname, GLfloat param);
extern void glInterfaceFog (GLenum pname, const GLfloat *params);
extern void glInterfaceFog (GLenum pname, GLint param);
extern void glInterfaceFog (GLenum pname, const GLint *params);
extern void glInterfaceFrontFace (GLenum mode);
extern void glInterfaceFrustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern GLuint glInterfaceGenLists (GLsizei range);
extern void glInterfaceGenTextures (GLsizei n, GLuint *textures);
extern void glInterfaceGetBooleanv (GLenum pname, GLboolean *params);
extern void glInterfaceGetClipPlane (GLenum plane, GLdouble *equation);
extern void glInterfaceGetColorTable (GLenum target, GLenum format, GLenum type, GLvoid *table);
extern void glInterfaceGetColorTableParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetColorTableParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetConvolutionFilter (GLenum target, GLenum format, GLenum type, GLvoid *image);
extern void glInterfaceGetConvolutionParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetConvolutionParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetDoublev (GLenum pname, GLdouble *params);
extern GLenum glInterfaceGetError (void);
extern void glInterfaceGetFloatv (GLenum pname, GLfloat *params);
extern void glInterfaceGetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values);
extern void glInterfaceGetHistogramParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetHistogramParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetIntegerv (GLenum pname, GLint *params);
extern void glInterfaceGetLight (GLenum light, GLenum pname, GLfloat *params);
extern void glInterfaceGetLight (GLenum light, GLenum pname, GLint *params);
extern void glInterfaceGetMap (GLenum target, GLenum query, GLdouble *v);
extern void glInterfaceGetMap (GLenum target, GLenum query, GLfloat *v);
extern void glInterfaceGetMap (GLenum target, GLenum query, GLint *v);
extern void glInterfaceGetMaterial (GLenum face, GLenum pname, GLfloat *params);
extern void glInterfaceGetMaterial (GLenum face, GLenum pname, GLint *params);
extern void glInterfaceGetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values);
extern void glInterfaceGetMinmaxParameter (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetMinmaxParameter (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetPixelMap (GLenum map, GLfloat *values);
extern void glInterfaceGetPixelMap (GLenum map, GLuint *values);
extern void glInterfaceGetPixelMap (GLenum map, GLushort *values);
extern void glInterfaceGetPointerv (GLenum pname, GLvoid **params);
extern void glInterfaceGetPolygonStipple (GLubyte *mask);
extern void glInterfaceGetSeparableFilter (GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span);
extern const GLubyte *glInterfaceGetString (GLenum name);
extern void glInterfaceGetTexEnv (GLenum target, GLenum pname, GLfloat *params);
extern void glInterfaceGetTexEnv (GLenum target, GLenum pname, GLint *params);
extern void glInterfaceGetTexGen (GLenum coord, GLenum pname, GLdouble *params);
extern void glInterfaceGetTexGen (GLenum coord, GLenum pname, GLfloat *params);
extern void glInterfaceGetTexGen (GLenum coord, GLenum pname, GLint *params);
